### ISSUE TITLE
defaultMetrics label transformer?

### ISSUE THREAD

**Issue by vendethiel** [worm2fed/servant-prometheus#6]
Hi,

The `defaultMetrics` variable is useful as a starting point, but if changes are needed (I needed to add a `source` field to differentiate different parts of my app) it's hard to do so without copy-pasting most of the code.

Is there a way to add a function to transform the `Metrics`, or maybe params to `mHttpRequestLatency`/`getHttpRequestLatencyLabels`/... to perform operations on them? (and `defaultMetrics` would just pass `id`).

Not sure what's the best way yet. Thanks!

**Comment by worm2fed** [comment]
@vendethiel hi!
sorry, somehow I've missed your issue..
will take a look a bit later

**Comment by worm2fed** [comment]
@vendethiel so, you want to have an extra label in your metric? smth like that:
```haskell
-- | Metric to measure HTTP server request latency.
mHttpRequestLatency :: RequestLatencyMetric P.Label4
mHttpRequestLatency =
  P.unsafeRegister
    . P.vector ("route_name", "method", "status_code", "source")
    $ P.histogram i P.defaultBuckets
  where
    i =
      P.Info
        "http_request_duration_seconds"
        "The HTTP server request latencies in seconds."
{-# NOINLINE mHttpRequestLatency #-}
```

am I right?
You see, this way type signature is changing as well (`P.Label4`)

actually, the reason why I've used that data:
```haskell
data Metrics mLatencyLabel mActiveLabel = Metrics
  { mLatency :: RequestLatencyMetric mLatencyLabel
  , mGetLatencyLabels :: Endpoint -> Status -> mLatencyLabel
  , mActive :: ActiveRequestsMetric mActiveLabel
  , mGetActiveLabels :: Endpoint -> mActiveLabel
  }
```

Exactly because I thought that someone will want to have another metrics.
So it should be completely fine to define your own `mLatency` and `mActive`. So it might seem that duplication of `mGetLatencyLabels` and `mGetActiveLabels` is not necessary, but this functions are so trivial
